const SET_IS_SELECTED_BIRD_EXIST = 'SET_IS_SELECTED_BIRD_EXIST';
const SET_SELECTED_BIRD = 'SET_SELECTED_BIRD';
const SET_IS_CORRECT_CURRENT_BIRD = 'SET_IS_CORRECT_CURRENT_BIRD';
const SET_BIRDS = 'SET_BIRDS';

export const actionTypes = {
  SET_IS_SELECTED_BIRD_EXIST,
  SET_SELECTED_BIRD,
  SET_IS_CORRECT_CURRENT_BIRD,
  SET_BIRDS,
};
