const SET_LEVEL = "SET_LEVEL";
const SET_TOTAL_SCORE = "SET_TOTAL_SCORE";
const RESET_TOTAL_SCORE = "RESET_TOTAL_SCORE";
const SET_SCORE_ON_THE_LEVEL = "SET_SCORE_ON_THE_LEVEL";
const IS_LEVEL_COMPLETED = "IS_LEVEL_COMPLETED";

export const actionTypes = {
  SET_LEVEL: SET_LEVEL,
  SET_TOTAL_SCORE: SET_TOTAL_SCORE,
  RESET_TOTAL_SCORE: RESET_TOTAL_SCORE,
  SET_SCORE_ON_THE_LEVEL: SET_SCORE_ON_THE_LEVEL,
  SET_IS_LEVEL_COMPLETED: IS_LEVEL_COMPLETED,
};
